# Generated by Django 4.0.3 on 2022-05-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adt',
            name='photo',
            field=models.ImageField(default=None, upload_to='photo/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='adt',
            name='adtCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='adt',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='adt',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='respond',
            name='responseAdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.adt', verbose_name='Adt'),
        ),
    ]
