# Generated by Django 4.0.3 on 2022-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adt_photo_alter_adt_adtcategory_alter_adt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adt',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
