# Generated by Django 4.0.3 on 2022-05-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_photo_remove_adt_photo_alter_adt_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
