# Generated by Django 4.0.3 on 2022-05-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_onetimecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
