# Generated by Django 4.0.3 on 2022-05-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_delete_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adt',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='author',
            name='ratingAuthor',
        ),
    ]
